Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/07/2024
Var
 i, x,vezes, tabuada: inteiro


Inicio
   escreval("Deseja a tabuada para qual valor? ")
   leia(tabuada)
   
   para i de 1 ate 10 faca

   x <- tabuada * i
   escreval(x)


   fimpara
   
   
   


Fimalgoritmo